color: null
fieldLayouts:
  5168a45a-ffa4-429b-a49c-282e07fa4910:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T10:40:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2f96dea9-b8cc-468d-9c40-caa869d8350a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T10:17:40+00:00'
            elementCondition: null
            fieldUid: ec5490fd-6fc4-4816-a24f-6d4b44bcbd18 # Navigation-item
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a4dfedc-4c12-4d53-a9f6-9e014e7f86d3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T18:35:22+00:00'
            elementCondition: null
            fieldUid: 23e6ccab-3f69-4063-b0a4-14e0a251fdef # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 850db830-6ccd-4196-8e07-2aac5ea1e25c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d15f5c75-f49d-48c8-97c0-f3a3ee166498
        userCondition: null
handle: navigation
hasTitleField: true
icon: null
name: Navigation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
