color: null
fieldLayouts:
  fec02491-81e1-44f2-86be-3b2040d20cea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-12T13:44:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 32a2668e-536f-4ac1-86a7-d5182536c531
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T09:58:05+00:00'
            elementCondition: null
            fieldUid: 23e6ccab-3f69-4063-b0a4-14e0a251fdef # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cce5a12-edd4-48ca-a579-63608bd2780a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T13:41:52+00:00'
            elementCondition: null
            fieldUid: b1d5a4db-a31a-42fc-a9d5-58c417d72456 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86b81de2-16a8-4372-8f6c-6c9cdcbc19c4
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: a38a71aa-bcb6-4612-af0f-d8cea774d8b9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-12T13:44:56+00:00'
            elementCondition: null
            fieldUid: 1627a97b-9bc6-47e2-9cbc-44f7510366ca # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abd5b5a8-56d6-4411-a5a9-a9e8878308d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T13:47:21+00:00'
            elementCondition: null
            fieldUid: 1da3952b-c5a6-4582-94b9-1355b053cf6b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3fc265c-d9ee-4b76-8059-0a4e1d159e55
            userCondition: null
            warning: null
            width: 100
        name: Detail
        uid: a5040d2b-3791-42a1-8402-337380462eca
        userCondition: null
handle: projects
hasTitleField: true
icon: list-check
name: Projects
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
