dateModified: 1744145606
email:
  fromEmail: basboyukhabip@gmail.com
  fromName: 'Portfolio - Habip Basboyuk'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
meta:
  __names__:
    00bb6892-c9eb-48a7-a7ce-b9da7fa7f3c2: contactPage # contactPage
    0dc4d883-275f-480b-9c4d-b9c76da6f521: ProfileImage # ProfileImage
    1da3952b-c5a6-4582-94b9-1355b053cf6b: 'Rich Text' # Rich Text
    2c59ad2c-fca1-4d43-b01b-2e659e38cdb7: 'plain text' # plain text
    3d866530-4836-4eb8-a5aa-570fa70ca4f6: 'Home Info' # Home Info
    5ea472df-7cf3-4fbe-b007-408189d80e0f: Skills # Skills
    23e6ccab-3f69-4063-b0a4-14e0a251fdef: Image # Image
    30a01e48-b0d3-4c5c-8019-4ff23b2919ee: Simple # Simple
    76a10a9c-5413-4b3f-be22-0031f1bce883: Navigation # Navigation
    270a05ae-3e38-4a15-9878-9305fd928086: Projects # Projects
    284aa496-0f8a-4ec0-a629-d9db0aedca53: Navigation # Navigation
    937e9aff-6c16-470a-896d-54f552cdedc5: Projects # Projects
    1627a97b-9bc6-47e2-9cbc-44f7510366ca: Images # Images
    3578b5c4-3eee-4f81-b25e-f3c3f452e62f: ProfilePicture # ProfilePicture
    5944be25-c46f-4c37-bdb0-be37d7234ae4: Info # Info
    14082bfa-b4e4-47b8-9863-ca1976106187: 'Portfolio - Habip Basboyuk' # Portfolio - Habip Basboyuk
    19263dfa-a60f-4180-9eea-d773be274e79: skillCard # skillCard
    5808659c-1340-4739-a959-36903f25849e: 'Skill page' # Skill page
    a5c3e1d1-e9d2-4ccf-ad1b-40111b4219ef: pageTitle # pageTitle
    b1d5a4db-a31a-42fc-a9d5-58c417d72456: Description # Description
    b3fd9a58-e334-4d3b-84c5-c933b1d7f0f0: heading # heading
    bc278b7d-22ae-4a72-9a8e-f3fc8733c1d7: project # project
    be1e85a1-2e0b-4e87-bf9b-1cfe3332051c: email # email
    cb351e85-de42-4cff-85ae-a89890ac3bd8: Images # Images
    ccb28842-2f68-4eb1-b7df-363dcf8a824b: 'Contact page' # Contact page
    e7f27143-a8ea-450d-a494-57c332c101fc: 'Home Page' # Home Page
    e24555e5-cbf7-4f7d-a9e1-e52cddfdd4f7: 'Portfolio - Habip Basboyuk' # Portfolio - Habip Basboyuk
    ec5490fd-6fc4-4816-a24f-6d4b44bcbd18: Navigation-item # Navigation-item
    ecdf347e-8b54-4d43-a72c-e833595db34b: numbers # numbers
    f6f38018-f84e-4925-97df-92360fc5d13d: 'Project Page' # Project Page
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from Portfolio - Habip Basboyuk'
      successFlashMessage: 'Your message has been sent.'
      toEmail: basboyukhabip@gmail.com
  freeform:
    edition: express
    enabled: true
    schemaVersion: 5.4.2
system:
  edition: solo
  live: true
  name: 'Portfolio - Habip Basboyuk'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
