defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 937e9aff-6c16-470a-896d-54f552cdedc5 # Projects
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  14082bfa-b4e4-47b8-9863-ca1976106187: # Portfolio - Habip Basboyuk
    enabledByDefault: true
    hasUrls: true
    template: _pages/_project-detail.twig
    uriFormat: 'project/{slug}'
structure:
  maxLevels: null
  uid: af401914-1b48-4008-bd46-188e305992eb
type: structure
